### PR TITLE
Updating pages to include Bitovi / DoneJS

### PR DESCRIPTION
**Pull request by tomgreever**
This updates all references to Juptier to Bitovi and updates Contact links to bitovi.com, plus a few small copy changes to promote Bitovi & DoneJS. 

I realize much more can be done and people will have opinions about how to best update this page. However, I'd like to go ahead and put these changes in production now. If there's further discussion / ideas about how to make it better, that's totally cool. Let's get this up first and then discuss.

cc @justinbmeyer @moschel  @retro 

screen shot 2015-12-28 at 2 49 00 pm

screen shot 2015-12-28 at 2 49 13 pm

### CODE REVIEW

**Comment by tomgreever** [comment]
Cool - how do we put it in production?

**Comment by moschel** [comment]
Great question. It's been over 4 years since this was last touched. I will have to dig a little and try to remember where it is deployed.

@alexisabril would be the other person who could probably figure this out but he's on PTO this week.

**Comment by matthewp** [comment]
The headers suggest it's probably Heroku.

**Comment by moschel** [comment]
Got it pushed out: http://www.embeddedjs.com/

**Pull request merged**
